### PR TITLE
Generate a context if one does not exist

### LINKED ISSUE #700: `library` before `context` throws error?
Hoping this is reproducible:

1.  Created a new R package (via new project) using RStudio.
2. `usethis::use_testthat()`
3. `usethis::use_test("example")`
4. Modify `test-example.R` to 

``` r
library(dplyr)

context("test-example.R")

test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```

5. `devtools::test()` gives

``` r
> devtools::test()
Loading tmp2
Testing tmp2
√ | OK F W S | Context
Error in x[[method]](...) : attempt to apply non-function

== Results =====================================================================
Duration: 0.2 s

OK:       0
Failed:   2
Warnings: 1
Skipped:  0
```

but if the `context` comes before `library` in `test-example.R`, everything works. Is this expected? I'm using `testthat 2.0.0`.

### LINKED ISSUE #705: Failed tests don't print in the progress section, but appear in the results
Hi there!

At [this commit](https://github.com/njtierney/naniar/commit/bf72c1322bc48634794ab55aca6de6864e5ae584) of naniar I get the following print message when I run devtools::test()

(apologies for hard coding the pkg PATH in the reprex, I couldn't get it to work otherwise!

The problem is that it doesn't print that I have 5 tests that failed, but shows me that I have 5 tests that failed.

When I run `devtools::check()` I can identify that the tests all fail in test-replace-with-na-where.

Perhaps I've missed something obvious, but thought you might like to know about this,

Thanks again for building and maintaining a package I use every day!

``` r
devtools::test("/Users/ntie0001/github/njtierney/naniar")
#> Loading naniar
#> Loading required package: testthat
#> Testing naniar
#> Warning: `encoding` is deprecated; all files now assumed to be UTF-8
#> ✔ | OK F W S | Context
#> 
⠏ |  0       | add_any_miss
⠋ |  1       | add_any_miss
⠙ |  2       | add_any_miss
⠹ |  3       | add_any_miss
⠸ |  4       | add_any_miss
⠼ |  5       | add_any_miss
⠴ |  6       | add_any_miss
⠦ |  7       | add_any_miss
✔ |  7       | add_any_miss [0.3 s]
#> 
⠏ |  0       | add_label_missings
⠋ |  1       | add_label_missings
⠙ |  2       | add_label_missings
⠹ |  3       | add_label_missings
✔ |  3       | add_label_missings
#> 
⠏ |  0       | add_label_shadow
⠋ |  1       | add_label_shadow
⠙ |  2       | add_label_shadow
⠹ |  3       | add_label_shadow
✔ |  3       | add_label_shadow
#> 
⠏ |  0       | add_n_miss
⠋ |  1       | add_n_miss
⠙ |  2       | add_n_miss
⠹ |  3       | add_n_miss
⠸ |  4       | add_n_miss
✔ |  4       | add_n_miss
#> 
⠏ |  0       | add_prop_miss
⠋ |  1       | add_prop_miss
⠙ |  2       | add_prop_miss
⠹ |  3       | add_prop_miss
⠸ |  4       | add_prop_miss
✔ |  4       | add_prop_miss
#> 
⠏ |  0       | add_shadow_shift
⠋ |  1       | add_shadow_shift
⠙ |  2       | add_shadow_shift
⠹ |  3       | add_shadow_shift
⠸ |  4       | add_shadow_shift
⠼ |  5       | add_shadow_shift
✔ |  5       | add_shadow_shift
#> 
⠏ |  0       | add_shadow
⠋ |  1       | add_shadow
⠙ |  2       | add_shadow
⠹ |  3       | add_shadow
⠸ |  4       | add_shadow
✔ |  4       | add_shadow
#> 
⠏ |  0       | as_shadow
⠋ |  1       | as_shadow
⠙ |  2       | as_shadow
⠹ |  3       | as_shadow
⠸ |  4       | as_shadow
⠼ |  5       | as_shadow
⠴ |  6       | as_shadow
⠦ |  7       | as_shadow
⠧ |  8       | as_shadow
⠇ |  9       | as_shadow
✔ |  9       | as_shadow
#> 
⠏ |  0       | bind_shadow
⠋ |  1       | bind_shadow
⠙ |  2       | bind_shadow
⠹ |  3       | bind_shadow
⠸ |  4       | bind_shadow
⠼ |  5       | bind_shadow
⠴ |  6       | bind_shadow
⠦ |  7       | bind_shadow
⠧ |  8       | bind_shadow
⠇ |  9       | bind_shadow
✔ |  9       | bind_shadow
#> 
⠏ |  0       | cast_shadow_shift_label
⠋ |  1       | cast_shadow_shift_label
⠙ |  2       | cast_shadow_shift_label
⠹ |  3       | cast_shadow_shift_label
⠸ |  4       | cast_shadow_shift_label
⠼ |  5       | cast_shadow_shift_label
⠴ |  6       | cast_shadow_shift_label
⠦ |  7       | cast_shadow_shift_label
⠧ |  8       | cast_shadow_shift_label
✔ |  8       | cast_shadow_shift_label [0.2 s]
#> 
⠏ |  0       | cast_shadow_shift
⠋ |  1       | cast_shadow_shift
⠙ |  2       | cast_shadow_shift
⠹ |  3       | cast_shadow_shift
⠸ |  4       | cast_shadow_shift
⠼ |  5       | cast_shadow_shift
⠴ |  6       | cast_shadow_shift
⠦ |  7       | cast_shadow_shift
⠧ |  8       | cast_shadow_shift
✔ |  8       | cast_shadow_shift [0.2 s]
#> 
⠏ |  0       | cast_shadow
⠋ |  1       | cast_shadow
⠙ |  2       | cast_shadow
⠹ |  3       | cast_shadow
⠸ |  4       | cast_shadow
⠼ |  5       | cast_shadow
⠴ |  6       | cast_shadow
⠦ |  7       | cast_shadow
✔ |  7       | cast_shadow [0.1 s]
#> 
⠏ |  0       | gather_shadow
⠋ |  1       | gather_shadow
⠙ |  2       | gather_shadow
⠹ |  3       | gather_shadow
⠸ |  4       | gather_shadow
⠼ |  5       | gather_shadow
⠴ |  6       | gather_shadow
⠦ |  7       | gather_shadow
⠧ |  8       | gather_shadow
⠇ |  9       | gather_shadow
✔ |  9       | gather_shadow [0.1 s]
#> 
⠏ |  0       | Label 1d missings
⠋ |  1       | Label 1d missings
⠙ |  2       | Label 1d missings
⠹ |  3       | Label 1d missings
⠸ |  4       | Label 1d missings
⠼ |  5       | Label 1d missings
⠴ |  6       | Label 1d missings
✔ |  6       | Label 1d missings
#> 
⠏ |  0       | Label 2d missings
⠋ |  1       | Label 2d missings
⠙ |  2       | Label 2d missings
⠹ |  3       | Label 2d missings
⠸ |  4       | Label 2d missings
⠼ |  5       | Label 2d missings
⠴ |  6       | Label 2d missings
⠦ |  7       | Label 2d missings
⠧ |  8       | Label 2d missings
✔ |  8       | Label 2d missings
#> 
⠏ |  0       | label_shadow_matrix behaves
⠋ |  1       | label_shadow_matrix behaves
⠙ |  2       | label_shadow_matrix behaves
⠹ |  3       | label_shadow_matrix behaves
⠸ |  4       | label_shadow_matrix behaves
✔ |  4       | label_shadow_matrix behaves
#> 
⠏ |  0       | label_shadow
⠋ |  1       | label_shadow
⠙ |  2       | label_shadow
⠹ |  3       | label_shadow
✔ |  3       | label_shadow
#> 
⠏ |  0       | miss_case_summary tidiers
⠋ |  1       | miss_case_summary tidiers
⠙ |  2       | miss_case_summary tidiers
⠹ |  3       | miss_case_summary tidiers
⠸ |  4       | miss_case_summary tidiers
⠼ |  5       | miss_case_summary tidiers
⠴ |  6       | miss_case_summary tidiers
⠦ |  7       | miss_case_summary tidiers
⠧ |  8       | miss_case_summary tidiers
⠇ |  9       | miss_case_summary tidiers
✔ |  9       | miss_case_summary tidiers [0.4 s]
#> 
⠏ |  0       | miss_case_table tidiers
⠋ |  1       | miss_case_table tidiers
⠙ |  2       | miss_case_table tidiers
⠹ |  3       | miss_case_table tidiers
⠸ |  4       | miss_case_table tidiers
⠼ |  5       | miss_case_table tidiers
⠴ |  6       | miss_case_table tidiers
⠦ |  7       | miss_case_table tidiers
⠧ |  8       | miss_case_table tidiers
⠇ |  9       | miss_case_table tidiers
⠏ | 10       | miss_case_table tidiers
✔ | 10       | miss_case_table tidiers [0.3 s]
#> 
⠏ |  0       | miss_prop_summary
⠋ |  1       | miss_prop_summary
⠙ |  2       | miss_prop_summary
⠹ |  3       | miss_prop_summary
⠸ |  4       | miss_prop_summary
⠼ |  5       | miss_prop_summary
⠴ |  6       | miss_prop_summary
⠦ |  7       | miss_prop_summary
⠧ |  8       | miss_prop_summary
⠇ |  9       | miss_prop_summary
⠏ | 10       | miss_prop_summary
⠋ | 11       | miss_prop_summary
⠙ | 12       | miss_prop_summary
⠹ | 13       | miss_prop_summary
✔ | 13       | miss_prop_summary [0.4 s]
#> 
⠏ |  0       | miss_summary
⠋ |  1       | miss_summary
⠙ |  2       | miss_summary
⠹ |  3       | miss_summary
⠸ |  4       | miss_summary
⠼ |  5       | miss_summary
⠴ |  6       | miss_summary
⠦ |  7       | miss_summary
⠧ |  8       | miss_summary
✔ |  8       | miss_summary [0.2 s]
#> 
⠏ |  0       | miss_var_summary tidiers
⠋ |  1       | miss_var_summary tidiers
⠙ |  2       | miss_var_summary tidiers
⠹ |  3       | miss_var_summary tidiers
⠸ |  4       | miss_var_summary tidiers
⠼ |  5       | miss_var_summary tidiers
⠴ |  6       | miss_var_summary tidiers
⠦ |  7       | miss_var_summary tidiers
⠧ |  8       | miss_var_summary tidiers
⠇ |  9       | miss_var_summary tidiers
⠏ | 10       | miss_var_summary tidiers
✔ | 10       | miss_var_summary tidiers [0.3 s]
#> 
⠏ |  0       | miss_var_table tidiers
⠋ |  1       | miss_var_table tidiers
⠙ |  2       | miss_var_table tidiers
⠹ |  3       | miss_var_table tidiers
⠸ |  4       | miss_var_table tidiers
⠼ |  5       | miss_var_table tidiers
⠴ |  6       | miss_var_table tidiers
⠦ |  7       | miss_var_table tidiers
⠧ |  8       | miss_var_table tidiers
⠇ |  9       | miss_var_table tidiers
⠏ | 10       | miss_var_table tidiers
✔ | 10       | miss_var_table tidiers [0.4 s]
#> 
⠏ |  0       | miss_*_pct tidiers
⠋ |  1       | miss_*_pct tidiers
⠙ |  2       | miss_*_pct tidiers
⠹ |  3       | miss_*_pct tidiers
⠸ |  4       | miss_*_pct tidiers
⠼ |  5       | miss_*_pct tidiers
⠴ |  6       | miss_*_pct tidiers
⠦ |  7       | miss_*_pct tidiers
⠧ |  8       | miss_*_pct tidiers
⠇ |  9       | miss_*_pct tidiers
⠏ | 10       | miss_*_pct tidiers
⠋ | 11       | miss_*_pct tidiers
⠙ | 12       | miss_*_pct tidiers
⠹ | 13       | miss_*_pct tidiers
⠸ | 14       | miss_*_pct tidiers
⠼ | 15       | miss_*_pct tidiers
✔ | 15       | miss_*_pct tidiers
#> 
⠏ |  0       | n_complete
⠋ |  1       | n_complete
⠙ |  2       | n_complete
⠹ |  3       | n_complete
⠸ |  4       | n_complete
⠼ |  5       | n_complete
⠴ |  6       | n_complete
⠦ |  7       | n_complete
✔ |  7       | n_complete
#> 
⠏ |  0       | n_miss
⠋ |  1       | n_miss
⠙ |  2       | n_miss
⠹ |  3       | n_miss
⠸ |  4       | n_miss
⠼ |  5       | n_miss
⠴ |  6       | n_miss
⠦ |  7       | n_miss
✔ |  7       | n_miss
#> 
⠏ |  0       | naniar-plots
#> 
⠋ |  1       | naniar-plots
#> 
⠙ |  2       | naniar-plots
#> 
⠹ |  3       | naniar-plots
#> 
⠸ |  4       | naniar-plots
#> 
⠼ |  5       | naniar-plots
#> 
⠴ |  6       | naniar-plots
✔ |  6       | naniar-plots [2.8 s]
#> 
⠏ |  0       | replace_with_na scoped variants
⠋ |  1       | replace_with_na scoped variants
⠙ |  2       | replace_with_na scoped variants
⠹ |  3       | replace_with_na scoped variants
⠸ |  4       | replace_with_na scoped variants
⠼ |  5       | replace_with_na scoped variants
⠴ |  6       | replace_with_na scoped variants
⠦ |  7       | replace_with_na scoped variants
⠧ |  8       | replace_with_na scoped variants
⠇ |  9       | replace_with_na scoped variants
⠏ | 10       | replace_with_na scoped variants
⠋ | 11       | replace_with_na scoped variants
✔ | 11       | replace_with_na scoped variants
#> 
⠙ | 12       | replace_with_na scoped variants
⠹ | 13       | replace_with_na scoped variants
⠸ | 13 1     | replace_with_na scoped variants
⠼ | 14 1     | replace_with_na scoped variants
⠴ | 15 1     | replace_with_na scoped variants
⠦ | 15 2     | replace_with_na scoped variants
⠧ | 16 2     | replace_with_na scoped variants
⠇ | 16 3     | replace_with_na scoped variants
⠏ | 16 4     | replace_with_na scoped variants
⠋ | 17 4     | replace_with_na scoped variants
⠙ | 17 5     | replace_with_na scoped variants
⠏ |  0       | replace_to_na deprecation test
⠋ |  1       | replace_to_na deprecation test
✔ |  1       | replace_to_na deprecation test
#> 
⠏ |  0       | replace_with_na
⠋ |  1       | replace_with_na
⠙ |  2       | replace_with_na
⠹ |  3       | replace_with_na
⠸ |  4       | replace_with_na
⠼ |  5       | replace_with_na
⠴ |  6       | replace_with_na
⠦ |  7       | replace_with_na
⠧ |  8       | replace_with_na
✔ |  8       | replace_with_na
#> 
⠏ |  0       | shadow shift
⠋ |  1       | shadow shift
⠙ |  2       | shadow shift
⠹ |  3       | shadow shift
⠸ |  4       | shadow shift
⠼ |  5       | shadow shift
⠴ |  6       | shadow shift
⠦ |  7       | shadow shift
⠧ |  8       | shadow shift
⠇ |  9       | shadow shift
✔ |  9       | shadow shift
#> 
#> ══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
#> Duration: 6.6 s
#> 
#> OK:       231
#> Failed:   5
#> Warnings: 0
#> Skipped:  0
#> 
#> No-one gets it right on their first try
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.3 (2017-11-30)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2018-01-17
#> Packages -----------------------------------------------------------------
#>  package           * version    date      
#>  assertthat          0.2.0      2017-04-11
#>  backports           1.1.2      2017-12-13
#>  base              * 3.4.3      2017-12-07
#>  bindr               0.1        2016-11-13
#>  bindrcpp          * 0.2        2017-06-17
#>  cli                 1.0.0      2017-11-05
#>  colorspace          1.3-2      2016-12-14
#>  commonmark          1.4        2017-09-01
#>  compiler            3.4.3      2017-12-07
#>  crayon              1.3.4      2017-10-09
#>  datasets          * 3.4.3      2017-12-07
#>  desc                1.1.1      2017-08-03
#>  devtools            1.13.4     2017-11-09
#>  digest              0.6.14     2018-01-14
#>  dplyr               0.7.4      2017-09-28
#>  evaluate            0.10.1     2017-06-24
#>  fontBitstreamVera   0.1.1      2017-02-01
#>  fontLiberation      0.1.0      2016-10-15
#>  fontquiver          0.2.1      2017-02-01
#>  forcats             0.2.0      2017-01-23
#>  formatR             1.5        2017-04-25
#>  gdtools           * 0.1.6      2017-09-01
#>  ggplot2           * 2.2.1.9000 2017-12-06
#>  glue                1.2.0      2017-10-29
#>  graphics          * 3.4.3      2017-12-07
#>  grDevices         * 3.4.3      2017-12-07
#>  grid                3.4.3      2017-12-07
#>  gridExtra           2.3        2017-09-09
#>  gtable              0.2.0      2016-02-26
#>  htmltools           0.3.6      2017-04-28
#>  knitr               1.17       2017-08-10
#>  labeling            0.3        2014-08-23
#>  lazyeval            0.2.1      2017-10-29
#>  magrittr            1.5        2014-11-22
#>  memoise             1.1.0      2017-04-21
#>  methods           * 3.4.3      2017-12-07
#>  munsell             0.4.3      2016-02-13
#>  naniar            * 0.1.4.9100 <NA>      
#>  pillar              1.1.0      2018-01-14
#>  pkgconfig           2.0.1      2017-03-21
#>  plyr                1.8.4      2016-06-08
#>  purrr               0.2.4      2017-10-18
#>  purrrlyr            0.0.2      2017-05-13
#>  R6                  2.2.2      2017-06-17
#>  Rcpp                0.12.14    2017-11-23
#>  rlang               0.1.6      2017-12-21
#>  rmarkdown           1.8        2017-11-17
#>  roxygen2            6.0.1.9000 2017-05-10
#>  rprojroot           1.3-1      2017-12-18
#>  scales              0.5.0.9000 2017-12-06
#>  stats             * 3.4.3      2017-12-07
#>  stringi             1.1.6      2017-11-17
#>  stringr             1.2.0      2017-02-18
#>  svglite             1.2.1      2017-09-11
#>  testthat          * 2.0.0      2017-12-13
#>  tibble              1.4.1      2017-12-25
#>  tidyr               0.7.2      2017-10-16
#>  tidyselect          0.2.3      2017-11-06
#>  tools               3.4.3      2017-12-07
#>  utils             * 3.4.3      2017-12-07
#>  vdiffr              0.2.1      2017-10-09
#>  viridis             0.4.0      2017-03-27
#>  viridisLite         0.2.0      2017-03-24
#>  visdat              0.2.2      2017-12-14
#>  withr               2.1.1      2017-12-19
#>  xml2                1.1.1      2017-01-24
#>  yaml                2.1.16     2017-12-12
#>  source                             
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.3)                     
#>  local                              
#>  cran (@0.1)                        
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.2)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.1)                     
#>  local                              
#>  Github (gaborcsardi/crayon@b5221ab)
#>  local                              
#>  CRAN (R 3.4.1)                     
#>  CRAN (R 3.4.2)                     
#>  CRAN (R 3.4.3)                     
#>  CRAN (R 3.4.2)                     
#>  cran (@0.10.1)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.1)                     
#>  Github (tidyverse/ggplot2@7b5c185) 
#>  cran (@1.2.0)                      
#>  local                              
#>  local                              
#>  local                              
#>  CRAN (R 3.4.1)                     
#>  CRAN (R 3.4.0)                     
#>  cran (@0.3.6)                      
#>  cran (@1.17)                       
#>  CRAN (R 3.4.0)                     
#>  cran (@0.2.1)                      
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.0)                     
#>  local                              
#>  CRAN (R 3.4.0)                     
#>  local                              
#>  CRAN (R 3.4.3)                     
#>  cran (@2.0.1)                      
#>  CRAN (R 3.4.0)                     
#>  cran (@0.2.4)                      
#>  CRAN (R 3.4.0)                     
#>  cran (@2.2.2)                      
#>  cran (@0.12.14)                    
#>  cran (@0.1.6)                      
#>  CRAN (R 3.4.2)                     
#>  Github (klutometis/roxygen@14eae41)
#>  CRAN (R 3.4.3)                     
#>  Github (hadley/scales@d767915)     
#>  local                              
#>  CRAN (R 3.4.2)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.1)                     
#>  CRAN (R 3.4.3)                     
#>  CRAN (R 3.4.3)                     
#>  CRAN (R 3.4.2)                     
#>  CRAN (R 3.4.2)                     
#>  local                              
#>  local                              
#>  CRAN (R 3.4.2)                     
#>  CRAN (R 3.4.0)                     
#>  cran (@0.2.0)                      
#>  local                              
#>  CRAN (R 3.4.3)                     
#>  CRAN (R 3.4.0)                     
#>  CRAN (R 3.4.3)
```

</details>

### PR DESCRIPTION
**Pull request by jimhester**
Test files without an explicit `context()` would cause

    Error in x[[method]](...) : attempt to apply non-function

errors in the Progress reporter. This generates a
context from the filename if there is not already a defined context,
fixing the issue.

Fixes #700
Fixes #705

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Should we cut the `test-` prefix?

**Comment by jimhester** [comment]
I am not really sure how we should test this. I was using a test file like the following

```r
test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})

context("blah")
context("blah2")

test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})

context("baz")

test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})

context("qux")
```

Which should generate output like

```
✔ | OK F W S | Context
✔ |  1       | test-blah.R
✔ |  0       | blah
✔ |  1       | blah2
✔ |  1       | baz
✔ |  0       | qux

══ Results ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
OK:       3
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by jimhester** [comment]
I wasn't sure about cutting the prefix (and possibly the extension?) or not. On one hand they are mostly redundant information, but on the other having the filename makes it easy to navigate to the relevant test file.

Keeping the full filename also makes it easy to transition to removing contexts #728, you can just remove the `context()` calls from the test files.

**Comment by gaborcsardi** [comment]
Looks like a good test to me.  But maybe I would compare the returned result of the reporter, not a the output? Or turn off Unicode and colors in the output.

File: R/reporter.R [hunk 1]
```diff
@@ -13,10 +13,12 @@ Reporter <- R6::R6Class("Reporter",
     start_reporter = function() {},
     start_context =  function(context) {},
     start_test =     function(context, test) {},
+    start_file =     function(filename) {},
     add_result =     function(context, test, result) {},
     end_test =       function(context, test) {},
     end_context =    function(context) {},
     end_reporter =   function() {},
+    end_file =       function() {},
```
Comment (jimhester) [inline R/reporter.R]: I added `end_file` even though I don't actually use it because we may need it in the future if we are removing context in favor of filenames.

File: R/test-files.R [hunk 2]
```diff
@@ -126,6 +126,7 @@ test_file <- function(path, reporter = default_reporter(), env = test_env(),
     reporter = reporter,
     start_end_reporter = start_end_reporter,
     {
+      get_reporter()$start_file(basename(path))
```
Comment (jimhester) [inline R/test-files.R]: We need to do this separately from the lister, because the lister is not part of the default reporter.

**Comment by gaborcsardi** [comment]
These are good points re cutting, but I think if we are to deprecate `context()` then it makes sense to still cut it, because it will be just a lot of redundant info.

Usually you want to go to the test file if sg fails there, and then you'll have the file name in the failure.

If we don't deprecate `context()` then it makes sense not to cut.

File: R/reporter-progress.R [hunk 3]
```diff
@@ -57,6 +58,16 @@ ProgressReporter <- R6::R6Class("ProgressReporter",
       self$show_header()
     },
 
+    start_file = function(file) {
+      self$file_name <- file
+    },
+
+    start_test = function(context, test) {
+      if (is.null(context)) {
+        context(self$file_name)
```
Comment (jimhester) [inline R/reporter-progress.R]: Using the regular `context()` function rather than `self$start_context()` or `self$.start_context()` because for the multi-reporter we need to assign `self$.context` in the multi-reporter rather than in the contained reporters.

File: R/test-files.R (hunk 2 above)
Comment (gaborcsardi) [reply R/test-files.R]: this would make a good comment in the source imo

File: R/reporter-progress.R (hunk 3 above)
Comment (gaborcsardi) [reply R/reporter-progress.R]: this one as well

File: NEWS.md [hunk 4]
```diff
@@ -8,6 +8,8 @@
 ## Minor improvements and bug fixes
 
 * Pass through warnings when `options(warn = 2)` is set (#721, @yutannihilation).
+* Progress reporter now generates a context from the filename and no longer
+  errors if tests occur before a context (#700, #705).
```
Comment (gaborcsardi) [inline NEWS.md]: Other reporters are OK without a context?

**Comment by jimhester** [comment]
Ok I added a few additional contexts to the `tests.R` file, which picked up a similar bug in the JUnit reporter when there is no context (also fixed). The rest of the reporters seem ok, but the expected outputs all changed as a result, so the diff is now big.

File: NEWS.md (hunk 4 above)
Comment (jimhester) [reply NEWS.md]: Yeah other than the JUnit one the rest seem ok

**Comment by hadley** [comment]
Yeah, I think we should remove the `test-` prefix and the `.R` suffix.  We'll also need to tweak the default context that usethis generates.

File: R/reporter-progress.R [hunk 5]
```diff
@@ -57,6 +58,22 @@ ProgressReporter <- R6::R6Class("ProgressReporter",
...
+        # We call the regular context() function rather than
+        # self$start_context() or self$.start_context() here because when this
+        # is called by a reporter inside the multi-reporter we need to assign
+        # self$.context in the multi-reporter rather than in the contained
+        # reporter.
+        context(self$file_name)
+      }
+    },
+
     start_context = function(context) {
```
Comment (hadley) [inline R/reporter-progress.R]: Should this all be moved to `start_file` or will you ignore `context()` calls in a different PR?

Comment (jimhester) [reply R/reporter-progress.R]: I was going to do that / discuss it in a separate PR

**Comment by jimhester** [comment]
Thank you both for the reviews!
