### PR TITLE
Rely on `load_all()` to load helpers

### LINKED ISSUE #1982: `test_active_file()` unloads helpers
```R
devtools::load_all()
devtools::test_active_file("R/active.R")
local_package_create
#> Error: ! object 'local_package_create' not found
```

### PR DESCRIPTION
**Pull request by hadley**
Otherwise effectively unload them for the developer. Fixes #1982

### CODE REVIEW

File: R/test-files.R [hunk 1]
```diff
@@ -197,6 +197,15 @@ test_files_serial <- function(test_dir,
                        load_package = c("none", "installed", "source"),
                        error_call = caller_env()) {
 
+  # Because load_all() called by test_files_setup_env() will have already
+  # loaded them. We don't want to rely on testthat's loading since that
+  # only affects the test environment and we want to keep the helpers
+  # looded in the users session.
```
Comment (DavisVaughan) [inline R/test-files.R:203]:
```suggestion
  # loaded in the user's session.
```

**Review by DavisVaughan — APPROVED** [review]
Confirmed that this fixes the problem for me. This was driving me nuts!

Before:

Screenshot 2024-10-23 at 9 04 18 AM


After:

Screenshot 2024-10-23 at 9 05 25 AM
