### PR TITLE
Show calls in errors

### LINKED ISSUE #1418: Show call in error
In testthat:

```R
Error: unused argument (paths[[1]])
Backtrace:
 1. testthat::expect_equal(...) test-utils.R:20:2
 2. testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3. testthat:::waldo_compare(...)
 4. waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)
 5. waldo:::compare_structure(x, y, paths = c(x_arg, y_arg), opts = opts) /Users/hadley/Documents/r-lib/waldo/R/compare.R:149:2
 6. waldo::compare_proxy(x, paths[[1]]) /Users/hadley/Documents/r-lib/waldo/R/compare.R:155:4
```

When called directly:

```R
Error in compare_proxy.spec_tbl_df(x, paths[[1]]) : unused argument (paths[[1]])
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #1418

### CODE REVIEW

File: R/expectation.R [hunk 1]
```diff
@@ -199,7 +190,13 @@ as.expectation.expectation <- function(x, srcref = NULL) {
 
 #' @export
 as.expectation.error <- function(x, srcref = NULL) {
-  expectation("error", cnd_message(x), srcref, trace = x[["trace"]])
+  if (is.null(x$call)) {
+    msg <- paste0("Error: ", cnd_message(x))
+  } else {
+    msg <- paste0("Error in ", expr_deparse(x$call[1]), ": ", cnd_message(x))
```
Comment (lionel-) [inline R/expectation.R:196]: `expr_deparse()` might return multiple lines in case of quoted `{` and inlined functions. In rlang complex expressions are skipped. I guess we want to strip arguments? The call should also be backticked.

Maybe it's easier to wait for rlang to export the relevant formatter?

Comment (hadley) [reply R/expectation.R:196]: Shouldn’t the `[1]` be sufficient?

Comment (lionel-) [reply R/expectation.R:196]: Not always because the CAR might be a complex expression. You could use `as_label()` instead.

Comment (hadley) [reply R/expectation.R:196]: Oooh yeah. Probably unlikely to affect us, but better to be safe.

Comment (lionel-) [reply R/expectation.R]: Did we want to also backtick the call for consistency with rlang errors?

Comment (hadley) [reply R/expectation.R]: Do we consistently backtick code? I thought we only did that for argument names?

Comment (lionel-) [reply R/expectation.R]: rlang is following cli formatting:

```r
cli::cli_text("{.code foo()}")
#> `foo()`
```

Personally I like the consistency with markdown syntax.

Comment (hadley) [reply R/expectation.R]: Makes sense. I'll fix momentarily.
