### PR TITLE
Enhance OO mocking

### LINKED ISSUE #2302: `local_mocked_s4_method()` doesn't work for generics from other packages

### PR DESCRIPTION
**Pull request by hadley**
Fixes #2302

### CODE REVIEW

File: R/mock-oo.R [hunk 1]
```diff
@@ -29,16 +30,43 @@ local_mocked_s3_method <- function(
 ) {
   check_string(generic)
   check_string(signature)
-  check_function(definition)
+  check_function(definition, allow_null = TRUE)
+
+  generic_def <- get(generic, envir = frame)
```
Comment (DavisVaughan) [inline R/mock-oo.R]: Unused. Remove?

File: R/mock-oo.R [hunk 2]
```diff
@@ -51,20 +79,28 @@ local_mocked_s4_method <- function(
...
+    if (is.null(def)) {
+      methods::removeMethod(generic_def, signature, env)
+    } else {
+      suppressMessages(methods::setMethod(generic_def, signature, def, env))
+    }
+    old
+  }
+
+  old <- set_method(definition)
+  withr::defer(set_method(old), frame)
```
Comment (DavisVaughan) [inline R/mock-oo.R]: Was it purposeful that `set_method()` locally captures `generic_def` and `signature` from the surrounding env rather than making them arguments? That kind of local capture always feels like a code smell to me (or when I _need_ it I drop a comment calling it out). I would have rather seen `set_method(generic_def, signature, def)` at each call site, where you see the full set of info required to set the method.

At the very least, I had to think about it for a minute when I saw `generic_def` in there but didn't see it defined anywhere, and had to backtrack up the outer function to find it.

File: tests/testthat/test-mock-oo.R [hunk 3]
```diff
@@ -16,10 +16,37 @@ test_that("validates its inputs", {
...
+    expect_length(x, 42)
+
+    # Now remove it
+    local_mocked_s3_method("length", "test_mock_class2", NULL)
+    expect_length(x, 0)
+  })
+
+  # Method should be removed after scope ends
+  expect_length(x, 0)
+})
```
Comment (DavisVaughan) [inline tests/testthat/test-mock-oo.R]: What about a test where `length.test_mock_class2` _does_ already exists before entering the `local()`, then you temporarily remove it for the `local()` scope, and then after exiting the local scope you ensure that the `old` definition was restored?

File: R/mock-oo.R [hunk 4]
```diff
@@ -29,16 +30,43 @@ local_mocked_s3_method <- function(
 ) {
   check_string(generic)
   check_string(signature)
-  check_function(definition)
+  check_function(definition, allow_null = TRUE)
+
+  generic_def <- get(generic, envir = frame)
```
[the remark this answers is not in the document]
Comment (hadley) [reply R/mock-oo.R]: I don't think it's worth it, as there's no simpler equivalent of `getGeneric()` for S3 generics and the existing error message is _ok_.

File: tests/testthat/test-mock-oo.R (hunk 3 above)
Comment (hadley) [reply tests/testthat/test-mock-oo.R]: Ah yeah, this test doesn't really focus on the removing. I'll improve.
