### PR TITLE
Tweaking skip messages

### LINKED ISSUE #868: tweak default messages for skip_if, skip_if_not
E.g.

```
> skip_if_not(FALSE)
Error: FALSE
```

It'd be nice if this showed something more like `Error: FALSE is not TRUE` or something with slightly more text.

As an example, the reported skip condition in `devtools::test()` is something like:

```
test-file.R:33: skip: we can do the thing
check_thing()
```

It would be a little more descriptive to instead write something like:

```
test-file.R:33: skip: we can do the thing
check_thing() is not TRUE
```

### PR DESCRIPTION
**Pull request by patr1ckm**
This addresses #868 by changes to the report messages in `skip`, `skip_if`, and `skip_if_not`. 

Examples of the new format are:

```
Reason: empty

tests.R:77: skip: Skip:4
Reason: condition is TRUE
```

The reference diff is a little noisier since I added a new test for `skip_if`.

EDIT: I'm skipping the `DebugReporter` output test unless the test is run interactively. The DebugReporter uses the package source to print relative debugging output. Since package source isn't available in R CMD CHECK, the test fails. 

Fixes #868 .

### CODE REVIEW

File: tests/testthat/test-reporter.R [hunk 1]
```diff
@@ -29,7 +29,7 @@ test_that("reporters produce consistent output", {
   expect_report_unchanged("teamcity")
   expect_report_unchanged("silent")
   expect_report_unchanged("rstudio")
-  expect_report_unchanged("junit", reporter = createJunitReporterMock())
```
Comment (patr1ckm) [inline tests/testthat/test-reporter.R]: This was refactored out earlier.

File: tests/testthat/reporters/debug.txt [hunk 2]
```diff
@@ -50,10 +50,13 @@
 1: tests.R#72: test_that("Skip:3", {
 })
 
-1: tests.R#78: warning("abc")
+1: tests.R#77: skip_if(condition)
+2: skip.R#86: skip(message)
```
Comment (patr1ckm) [inline tests/testthat/reporters/debug.txt]: This is the line that produced different output in `R CMD CHECK`. That showed only

`2: skip(message)`
rather than
`2: skip.R#86: skip(message)`

I'm still not sure what the bug is, but I think it may be an issue in `recover2`, which seems out of scope for this PR.

Comment (hadley) [reply tests/testthat/reporters/debug.txt]: I don't see this failure, either locally or on travis?

Comment (hadley) [reply tests/testthat/reporters/debug.txt]: Oh hmmm, seems like there's some problem with the reporter tests. I'll look into it

Comment (hadley) [reply tests/testthat/reporters/debug.txt]: Maybe this is #851?

Comment (hadley) [reply tests/testthat/reporters/debug.txt]: Ok, now I see the problem

Comment (hadley) [reply tests/testthat/reporters/debug.txt]: For now the easiest thing is just to remove that new skip. There are easier ways to test the output.
